In [1]:
print('hello')

hello

In [51]:
import pandas as pd
pd.set_option('display.max_columns', None)
df=pd.read_csv('contest_496/weekly_contest496.csv')
df.head()

,Rank,User_slug,Score,CurrConSolved,FinishTimeStamp,Q1TimeStamp,Q2TimeStamp,Q3TimeStamp,Q4TimeStamp,Q1FailCnt,Q2FailCnt,Q3FailCnt,Q4FailCnt,UserName,CountryName,RankingP,PostViewCnt,Reputation,TotalQsAcc,TotalQsSub,EasyQsAcc,EasyQsSub,MedQsAcc,MedQsSub,HardQsAcc,HardQsSub,ContestCnt,CurrRating,GlobalRank,topPercentage,ContestHistory
0,1,VeritasVelata,20,4,1775356616,1.775356e+09,1.775356e+09,1.775356e+09,1.775357e+09,0.0,0.0,0.0,0.0,Veritas Velata,Sanctuary,19,18693,137,3893,4873,935,1212,2037,2589,921,1072,23,3321.441119,25,0.01,"[{""attended"": true, ""trendDirection"": ""UP"", ""p..."
1,2,ayushkumar980,20,4,1775356691,1.775356e+09,1.775356e+09,1.775356e+09,1.775357e+09,0.0,0.0,0.0,0.0,ayushkumar980,India,1433822,4,0,106,115,23,24,53,57,30,34,16,3109.443766,77,0.01,"[{""attended"": true, ""trendDirection"": ""UP"", ""p..."
2,3,raunak111,20,4,1775356699,1.775356e+09,1.775356e+09,1.775356e+09,1.775357e+09,0.0,0.0,0.0,0.0,Raunak Prajapati,India,341067,7,0,358,516,121,198,196,274,41,44,8,1721.920546,99577,11.75,"[{""attended"": true, ""trendDirection"": ""DOWN"", ..."
3,4,Mona0405,20,4,1775356752,1.775356e+09,1.775356e+09,1.775356e+09,1.775357e+09,0.0,0.0,0.0,0.0,Arsyl5eIP3,NaN,1557154,0,0,95,96,24,24,48,49,23,23,1,2058.391571,15295,1.85,"[{""attended"": true, ""trendDirection"": ""UP"", ""p..."
4,5,scale5558,20,4,1775356771,1.775356e+09,1.775356e+09,1.775356e+09,1.775357e+09,0.0,0.0,0.0,0.0,scale5558,NaN,112045,0,4,628,646,168,169,338,341,122,136,7,2283.780248,4752,0.58,"[{""attended"": true, ""trendDirection"": ""UP"", ""p..."

In [42]:
df.shape

(9408, 31)

In [43]:
df.describe()

,Rank,Score,CurrConSolved,FinishTimeStamp,Q1TimeStamp,Q2TimeStamp,Q3TimeStamp,Q4TimeStamp,Q1FailCnt,Q2FailCnt,Q3FailCnt,Q4FailCnt,RankingP,PostViewCnt,Reputation,TotalQsAcc,TotalQsSub,EasyQsAcc,EasyQsSub,MedQsAcc,MedQsSub,HardQsAcc,HardQsSub,ContestCnt,CurrRating,GlobalRank,topPercentage
count,9408.000000,9408.000000,9408.000000,9.408000e+03,9.383000e+03,9.383000e+03,3.863000e+03,1.174000e+03,9383.000000,9383.000000,3863.000000,1174.000000,9.408000e+03,9408.000000,9408.000000,9408.000000,9408.000000,9408.000000,9408.000000,9408.000000,9408.000000,9408.000000,9408.000000,9408.000000,9408.000000,9408.000000,9408.000000
mean,5093.067708,11.764243,2.530081,1.775359e+09,1.775357e+09,1.775358e+09,1.775360e+09,1.775360e+09,0.267612,0.417137,1.714471,1.305792,8.926583e+05,892.776254,15.766263,459.290179,779.845876,160.446747,253.366815,244.802296,426.572810,54.041135,99.900298,30.455995,1758.087367,136358.367560,16.003249
std,2870.792550,3.618913,0.676685,1.716646e+03,7.260174e+02,8.027323e+02,1.208230e+03,1.247440e+03,0.570263,0.981133,1.722461,1.789717,1.295719e+06,12155.299897,139.205710,445.121545,1182.320926,135.451548,293.909522,250.065180,672.940693,89.102373,280.354204,47.454648,210.389451,125756.259161,14.622710
min,1.000000,9.000000,2.000000,1.775356e+09,1.775356e+09,1.775356e+09,1.775356e+09,1.775357e+09,0.000000,0.000000,0.000000,0.000000,8.000000e+00,0.000000,-8.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1328.058130,25.000000,0.010000
25%,2619.500000,9.000000,2.000000,1.775358e+09,1.775357e+09,1.775357e+09,1.775359e+09,1.775359e+09,0.000000,0.000000,1.000000,0.000000,1.149028e+05,0.000000,0.000000,160.000000,204.000000,62.000000,80.000000,72.000000,89.750000,7.000000,9.000000,8.000000,1609.115425,46884.500000,5.570000
50%,5141.500000,9.000000,2.000000,1.775359e+09,1.775357e+09,1.775358e+09,1.775360e+09,1.775360e+09,0.000000,0.000000,1.000000,0.000000,3.384305e+05,0.000000,0.000000,360.000000,515.000000,133.000000,191.000000,182.000000,257.000000,27.000000,36.000000,17.000000,1721.397774,99842.500000,11.780000
75%,7578.250000,14.000000,3.000000,1.775361e+09,1.775358e+09,1.775359e+09,1.775361e+09,1.775361e+09,0.000000,1.000000,2.000000,2.000000,9.732690e+05,13.000000,1.000000,622.250000,932.250000,223.000000,337.250000,334.000000,514.000000,63.000000,93.250000,34.000000,1861.735315,189668.750000,22.260000
max,10000.000000,20.000000,4.000000,1.775370e+09,1.775361e+09,1.775361e+09,1.775362e+09,1.775362e+09,3.000000,13.000000,10.000000,7.000000,5.000001e+06,729260.000000,4209.000000,3893.000000,29767.000000,935.000000,9445.000000,2037.000000,17564.000000,921.000000,7180.000000,632.000000,3321.441119,827070.000000,95.610000

In [52]:
#without any
df.dtypes

Rank                 int64
User_slug              str
Score                int64
CurrConSolved        int64
FinishTimeStamp      int64
Q1TimeStamp        float64
Q2TimeStamp        float64
Q3TimeStamp        float64
Q4TimeStamp        float64
Q1FailCnt          float64
Q2FailCnt          float64
Q3FailCnt          float64
Q4FailCnt          float64
UserName               str
CountryName            str
RankingP             int64
PostViewCnt          int64
Reputation           int64
TotalQsAcc           int64
TotalQsSub           int64
EasyQsAcc            int64
EasyQsSub            int64
MedQsAcc             int64
MedQsSub             int64
HardQsAcc            int64
HardQsSub            int64
ContestCnt           int64
CurrRating         float64
GlobalRank           int64
topPercentage      float64
ContestHistory         str
dtype: object

convert into suitable data types and handling null values

In [53]:

# df2=df results in same dataframe reference no copy is made
df2=df.copy()
df2['Q1TimeStamp'] = df2['Q1TimeStamp'].fillna(0).astype('int64')
df2['Q2TimeStamp'] = df2['Q2TimeStamp'].fillna(0).astype('int64')
df2['Q3TimeStamp'] = df2['Q3TimeStamp'].fillna(0).astype('int64')
df2['Q4TimeStamp'] = df2['Q4TimeStamp'].fillna(0).astype('int64')

df2['Q1FailCnt'] = df2['Q1FailCnt'].fillna(0).astype('int64')
df2['Q2FailCnt'] = df2['Q2FailCnt'].fillna(0).astype('int64')
df2['Q3FailCnt'] = df2['Q3FailCnt'].fillna(0).astype('int64')
df2['Q4FailCnt'] = df2['Q4FailCnt'].fillna(0).astype('int64')

df2['CurrRating'] = df2['CurrRating'].astype('int64')


df2.iloc[0:5]

,Rank,User_slug,Score,CurrConSolved,FinishTimeStamp,Q1TimeStamp,Q2TimeStamp,Q3TimeStamp,Q4TimeStamp,Q1FailCnt,Q2FailCnt,Q3FailCnt,Q4FailCnt,UserName,CountryName,RankingP,PostViewCnt,Reputation,TotalQsAcc,TotalQsSub,EasyQsAcc,EasyQsSub,MedQsAcc,MedQsSub,HardQsAcc,HardQsSub,ContestCnt,CurrRating,GlobalRank,topPercentage,ContestHistory
0,1,VeritasVelata,20,4,1775356616,1775356278,1775356366,1775356478,1775356616,0,0,0,0,Veritas Velata,Sanctuary,19,18693,137,3893,4873,935,1212,2037,2589,921,1072,23,3321,25,0.01,"[{""attended"": true, ""trendDirection"": ""UP"", ""p..."
1,2,ayushkumar980,20,4,1775356691,1775356278,1775356366,1775356478,1775356616,0,0,0,0,ayushkumar980,India,1433822,4,0,106,115,23,24,53,57,30,34,16,3109,77,0.01,"[{""attended"": true, ""trendDirection"": ""UP"", ""p..."
2,3,raunak111,20,4,1775356699,1775356278,1775356366,1775356478,1775356616,0,0,0,0,Raunak Prajapati,India,341067,7,0,358,516,121,198,196,274,41,44,8,1721,99577,11.75,"[{""attended"": true, ""trendDirection"": ""DOWN"", ..."
3,4,Mona0405,20,4,1775356752,1775356278,1775356366,1775356478,1775356616,0,0,0,0,Arsyl5eIP3,NaN,1557154,0,0,95,96,24,24,48,49,23,23,1,2058,15295,1.85,"[{""attended"": true, ""trendDirection"": ""UP"", ""p..."
4,5,scale5558,20,4,1775356771,1775356278,1775356366,1775356478,1775356616,0,0,0,0,scale5558,NaN,112045,0,4,628,646,168,169,338,341,122,136,7,2283,4752,0.58,"[{""attended"": true, ""trendDirection"": ""UP"", ""p..."

In [54]:

df.iloc[5000:5005] #original array

,Rank,User_slug,Score,CurrConSolved,FinishTimeStamp,Q1TimeStamp,Q2TimeStamp,Q3TimeStamp,Q4TimeStamp,Q1FailCnt,Q2FailCnt,Q3FailCnt,Q4FailCnt,UserName,CountryName,RankingP,PostViewCnt,Reputation,TotalQsAcc,TotalQsSub,EasyQsAcc,EasyQsSub,MedQsAcc,MedQsSub,HardQsAcc,HardQsSub,ContestCnt,CurrRating,GlobalRank,topPercentage,ContestHistory
5000,7239,GOUD_17,9,2,1775358295,1.775357e+09,1.775358e+09,NaN,NaN,1.0,0.0,NaN,NaN,anikethgoud5,NaN,670522,0,0,223,246,105,115,109,122,9,9,41,1737.610338,91300,10.78,"[{""attended"": true, ""trendDirection"": ""DOWN"", ..."
5001,7240,comvignesh01,9,2,1775358296,1.775357e+09,1.775358e+09,NaN,NaN,1.0,0.0,NaN,NaN,Vignesh N,NaN,1274512,0,0,120,145,58,73,54,62,8,10,19,1751.221438,84841,10.03,"[{""attended"": true, ""trendDirection"": ""DOWN"", ..."
5002,7241,Shinthya_21,9,2,1775358296,1.775357e+09,1.775358e+09,NaN,NaN,1.0,0.0,NaN,NaN,Shinthya_21,India,595003,0,0,247,257,105,110,117,122,25,25,8,1420.524552,637983,74.05,"[{""attended"": true, ""trendDirection"": ""DOWN"", ..."
5003,7242,Madhyam_17,9,2,1775358296,1.775357e+09,1.775358e+09,NaN,NaN,1.0,0.0,NaN,NaN,Madhyam_17,NaN,2327812,0,0,54,69,15,23,34,41,5,5,3,1614.827539,183505,21.54,"[{""attended"": true, ""trendDirection"": ""DOWN"", ..."
5004,7243,sachi777,9,2,1775358297,1.775357e+09,1.775358e+09,NaN,NaN,1.0,0.0,NaN,NaN,Sachi,NaN,1055456,0,0,147,259,91,166,52,89,4,4,6,1578.752023,227451,26.66,"[{""attended"": true, ""trendDirection"": ""UP"", ""p..."

time conversion from EPOCH to UTC time

In [55]:

#opetional can directly subtract epoch time to find differences in second and find time for each question
df2['FinishTimeStamp']=pd.to_datetime(df2['FinishTimeStamp'],unit='s')
df2['Q1TimeStamp']=pd.to_datetime(df2['Q1TimeStamp'],unit='s')
df2['Q2TimeStamp']=pd.to_datetime(df2['Q2TimeStamp'],unit='s')
df2['Q3TimeStamp']=pd.to_datetime(df2['Q3TimeStamp'],unit='s')
df2['Q4TimeStamp']=pd.to_datetime(df2['Q4TimeStamp'],unit='s')

df2.head()

,Rank,User_slug,Score,CurrConSolved,FinishTimeStamp,Q1TimeStamp,Q2TimeStamp,Q3TimeStamp,Q4TimeStamp,Q1FailCnt,Q2FailCnt,Q3FailCnt,Q4FailCnt,UserName,CountryName,RankingP,PostViewCnt,Reputation,TotalQsAcc,TotalQsSub,EasyQsAcc,EasyQsSub,MedQsAcc,MedQsSub,HardQsAcc,HardQsSub,ContestCnt,CurrRating,GlobalRank,topPercentage,ContestHistory
0,1,VeritasVelata,20,4,2026-04-05 02:36:56,2026-04-05 02:31:18,2026-04-05 02:32:46,2026-04-05 02:34:38,2026-04-05 02:36:56,0,0,0,0,Veritas Velata,Sanctuary,19,18693,137,3893,4873,935,1212,2037,2589,921,1072,23,3321,25,0.01,"[{""attended"": true, ""trendDirection"": ""UP"", ""p..."
1,2,ayushkumar980,20,4,2026-04-05 02:38:11,2026-04-05 02:31:18,2026-04-05 02:32:46,2026-04-05 02:34:38,2026-04-05 02:36:56,0,0,0,0,ayushkumar980,India,1433822,4,0,106,115,23,24,53,57,30,34,16,3109,77,0.01,"[{""attended"": true, ""trendDirection"": ""UP"", ""p..."
2,3,raunak111,20,4,2026-04-05 02:38:19,2026-04-05 02:31:18,2026-04-05 02:32:46,2026-04-05 02:34:38,2026-04-05 02:36:56,0,0,0,0,Raunak Prajapati,India,341067,7,0,358,516,121,198,196,274,41,44,8,1721,99577,11.75,"[{""attended"": true, ""trendDirection"": ""DOWN"", ..."
3,4,Mona0405,20,4,2026-04-05 02:39:12,2026-04-05 02:31:18,2026-04-05 02:32:46,2026-04-05 02:34:38,2026-04-05 02:36:56,0,0,0,0,Arsyl5eIP3,NaN,1557154,0,0,95,96,24,24,48,49,23,23,1,2058,15295,1.85,"[{""attended"": true, ""trendDirection"": ""UP"", ""p..."
4,5,scale5558,20,4,2026-04-05 02:39:31,2026-04-05 02:31:18,2026-04-05 02:32:46,2026-04-05 02:34:38,2026-04-05 02:36:56,0,0,0,0,scale5558,NaN,112045,0,4,628,646,168,169,338,341,122,136,7,2283,4752,0.58,"[{""attended"": true, ""trendDirection"": ""UP"", ""p..."

In [58]:
df2.iloc[5000:5100]

,Rank,User_slug,Score,CurrConSolved,FinishTimeStamp,Q1TimeStamp,Q2TimeStamp,Q3TimeStamp,Q4TimeStamp,Q1FailCnt,Q2FailCnt,Q3FailCnt,Q4FailCnt,UserName,CountryName,RankingP,PostViewCnt,Reputation,TotalQsAcc,TotalQsSub,EasyQsAcc,EasyQsSub,MedQsAcc,MedQsSub,HardQsAcc,HardQsSub,ContestCnt,CurrRating,GlobalRank,topPercentage,ContestHistory
5000,7239,GOUD_17,9,2,2026-04-05 03:04:55,2026-04-05 02:51:13,2026-04-05 02:59:51,1970-01-01,1970-01-01,1,0,0,0,anikethgoud5,NaN,670522,0,0,223,246,105,115,109,122,9,9,41,1737,91300,10.78,"[{""attended"": true, ""trendDirection"": ""DOWN"", ..."
5001,7240,comvignesh01,9,2,2026-04-05 03:04:56,2026-04-05 02:51:13,2026-04-05 02:59:51,1970-01-01,1970-01-01,1,0,0,0,Vignesh N,NaN,1274512,0,0,120,145,58,73,54,62,8,10,19,1751,84841,10.03,"[{""attended"": true, ""trendDirection"": ""DOWN"", ..."
5002,7241,Shinthya_21,9,2,2026-04-05 03:04:56,2026-04-05 02:51:13,2026-04-05 02:59:51,1970-01-01,1970-01-01,1,0,0,0,Shinthya_21,India,595003,0,0,247,257,105,110,117,122,25,25,8,1420,637983,74.05,"[{""attended"": true, ""trendDirection"": ""DOWN"", ..."
5003,7242,Madhyam_17,9,2,2026-04-05 03:04:56,2026-04-05 02:51:13,2026-04-05 02:59:51,1970-01-01,1970-01-01,1,0,0,0,Madhyam_17,NaN,2327812,0,0,54,69,15,23,34,41,5,5,3,1614,183505,21.54,"[{""attended"": true, ""trendDirection"": ""DOWN"", ..."
5004,7243,sachi777,9,2,2026-04-05 03:04:57,2026-04-05 02:51:13,2026-04-05 02:59:51,1970-01-01,1970-01-01,1,0,0,0,Sachi,NaN,1055456,0,0,147,259,91,166,52,89,4,4,6,1578,227451,26.66,"[{""attended"": true, ""trendDirection"": ""UP"", ""p..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5095,7337,Kshitij_saxena,9,2,2026-04-05 03:05:39,2026-04-05 02:57:13,2026-04-05 03:05:32,1970-01-01,1970-01-01,0,0,0,0,KSHITIJ,India,40212,711,19,907,1189,423,586,423,533,61,70,52,1690,118589,13.97,"[{""attended"": true, ""trendDirection"": ""DOWN"", ..."
5096,7338,kunaltiwari__,9,2,2026-04-05 03:05:39,2026-04-05 02:57:13,2026-04-05 03:05:32,1970-01-01,1970-01-01,0,0,0,0,KunalTiwari,NaN,138682,0,0,574,767,260,368,277,358,37,41,12,1643,155469,18.28,"[{""attended"": true, ""trendDirection"": ""UP"", ""p..."
5097,7339,soamA,9,2,2026-04-05 03:05:39,2026-04-05 02:57:13,2026-04-05 03:05:32,1970-01-01,1970-01-01,0,0,0,0,Sky,NaN,5155,0,2,1584,3719,516,1070,916,2279,152,370,129,1867,45144,5.37,"[{""attended"": true, ""trendDirection"": ""DOWN"", ..."
5098,7340,Priyanka_Valavala,9,2,2026-04-05 03:05:40,2026-04-05 02:57:13,2026-04-05 03:05:32,1970-01-01,1970-01-01,0,0,0,0,Priyanka_Valavala,NaN,1257842,0,0,122,133,60,65,56,61,6,7,11,1489,407643,47.55,"[{""attended"": true, ""trendDirection"": ""DOWN"", ..."
5099,7341,ranjan_vh,9,2,2026-04-05 03:05:40,2026-04-05 02:57:13,2026-04-05 03:05:32,1970-01-01,1970-01-01,0,0,0,0,ranjan05,India,279110,0,0,404,633,142,223,232,362,30,48,12,1766,78105,9.24,"[{""attended"": true, ""trendDirection"": ""UP"", ""p..."