EDA on training data only

In [2]:
import pandas as pd

pd.set_option('display.max_columns', None)
df=pd.read_csv('training_data.csv')
df.shape
# df[df['Rank']==2106]
df[df['User_slug']=='srikeerthi12']
# df[df['Rank']==1532]

,Rank,User_slug,Score,CurrConSolved,FinishTimeStamp,Q1TimeStamp,Q2TimeStamp,Q3TimeStamp,Q4TimeStamp,Q1FailCnt,Q2FailCnt,Q3FailCnt,Q4FailCnt,UserName,CountryName,RankingP,PostViewCnt,Reputation,TotalQsAcc,TotalQsSub,EasyQsAcc,EasyQsSub,MedQsAcc,MedQsSub,HardQsAcc,HardQsSub,ContestCnt,CurrRating,GlobalRank,topPercentage,ContestHistory,contest_id
10534,5449,srikeerthi12,9,2,2026-04-05 02:51:59,2026-04-05 02:40:53,2026-04-05 02:51:59,1970-01-01 00:00:00,1970-01-01 00:00:00,0,0,0,0,Srikeerthi Dindu,NaN,355712,0,0,349,451,119,153,202,266,28,32,18,1906.0,36950,4.41,"[{""attended"": true, ""trendDirection"": ""UP"", ""p...",3

In [4]:
df.columns

Index(['Rank', 'User_slug', 'Score', 'CurrConSolved', 'FinishTimeStamp',
       'Q1TimeStamp', 'Q2TimeStamp', 'Q3TimeStamp', 'Q4TimeStamp', 'Q1FailCnt',
       'Q2FailCnt', 'Q3FailCnt', 'Q4FailCnt', 'UserName', 'CountryName',
       'RankingP', 'PostViewCnt', 'Reputation', 'TotalQsAcc', 'TotalQsSub',
       'EasyQsAcc', 'EasyQsSub', 'MedQsAcc', 'MedQsSub', 'HardQsAcc',
       'HardQsSub', 'ContestCnt', 'CurrRating', 'GlobalRank', 'topPercentage',
       'ContestHistory'],
      dtype='str')

In [6]:
df.head()

,Rank,User_slug,Score,CurrConSolved,FinishTimeStamp,Q1TimeStamp,Q2TimeStamp,Q3TimeStamp,Q4TimeStamp,Q1FailCnt,Q2FailCnt,Q3FailCnt,Q4FailCnt,UserName,CountryName,RankingP,PostViewCnt,Reputation,TotalQsAcc,TotalQsSub,EasyQsAcc,EasyQsSub,MedQsAcc,MedQsSub,HardQsAcc,HardQsSub,ContestCnt,CurrRating,GlobalRank,topPercentage,ContestHistory
0,1,sunnynguyenai,18,4,1774147102,1.774147e+09,1.774147e+09,1.774147e+09,1.774147e+09,0.0,0.0,0.0,0.0,Sunny Nguyen,United States,870517,53,15,178,289,65,89,90,136,23,64,7,2347.059267,3415,0.42,"[{""attended"": true, ""trendDirection"": ""DOWN"", ..."
1,3,himank028,18,4,1774147143,1.774147e+09,1.774147e+09,1.774147e+09,1.774147e+09,0.0,0.0,0.0,0.0,Himank Gupta,NaN,4946519,0,0,13,14,2,2,6,6,5,6,3,2188.433504,7859,0.96,"[{""attended"": true, ""trendDirection"": ""UP"", ""p..."
2,4,hfgdnnvnxfg,18,4,1774147151,1.774147e+09,1.774147e+09,1.774147e+09,1.774147e+09,0.0,0.0,0.0,0.0,hfgdnnvnxfg,NaN,3497921,0,0,28,28,7,7,14,14,7,7,1,2047.222137,16114,1.95,"[{""attended"": true, ""trendDirection"": ""UP"", ""p..."
3,5,dark_knight_bt,18,4,1774147191,1.774147e+09,1.774147e+09,1.774147e+09,1.774147e+09,0.0,0.0,0.0,0.0,phoenix,China,156871,4,0,542,1062,191,345,300,636,51,81,52,2449.597491,2061,0.25,"[{""attended"": true, ""trendDirection"": ""DOWN"", ..."
4,6,ayushkumar980,18,4,1774147203,1.774147e+09,1.774147e+09,1.774147e+09,1.774147e+09,0.0,0.0,0.0,0.0,ayushkumar980,India,1433822,4,0,106,115,23,24,53,57,30,34,16,3109.443766,77,0.01,"[{""attended"": true, ""trendDirection"": ""UP"", ""p..."

In [ ]:
#sort the increasing order of total problems

In [ ]:
df.sort_values(by='TotalQsAcc')

,Rank,User_slug,Score,CurrConSolved,FinishTimeStamp,Q1TimeStamp,Q2TimeStamp,Q3TimeStamp,Q4TimeStamp,Q1FailCnt,Q2FailCnt,Q3FailCnt,Q4FailCnt,UserName,CountryName,RankingP,PostViewCnt,Reputation,TotalQsAcc,TotalQsSub,EasyQsAcc,EasyQsSub,MedQsAcc,MedQsSub,HardQsAcc,HardQsSub,ContestCnt,CurrRating,GlobalRank,topPercentage,ContestHistory,contest_id
10678,2552,EndlessZheng,14,3,2026-04-05 03:41:23,2026-04-05 02:39:37,2026-04-05 02:45:53,2026-04-05 03:26:22,1970-01-01 00:00:00,1,0,2,0,EndlessZheng,NaN,5000001,0,0,0,0,0,0,0,0,0,0,1,1950.0,666006,77.27,[],3
777,223,inhng,18,4,2026-03-22 03:08:25,2026-03-22 02:41:18,2026-03-22 03:01:33,2026-03-22 03:00:08,2026-03-22 02:48:43,1,0,0,0,InHng,中国,5000001,0,0,0,0,0,0,0,0,0,0,28,2322.0,3843,0.47,[],1
1125,8994,lain12,8,2,2026-03-22 03:37:56,2026-03-22 02:33:15,1970-01-01 00:00:00,2026-03-22 03:28:34,1970-01-01 00:00:00,0,0,1,0,Lain12,中国,5000001,0,0,0,0,0,0,0,0,0,0,7,1580.0,225463,26.43,[],1
10811,868,berriescream,20,4,2026-04-05 04:11:11,2026-04-05 02:46:57,2026-04-05 02:58:00,2026-04-05 03:29:33,2026-04-05 03:55:18,1,0,1,1,BerriesCream,NaN,5000001,0,0,0,0,0,0,0,0,0,0,15,1605.0,5610,0.69,[],3
618,7178,trdtrdsd,12,3,2026-03-22 03:50:33,2026-03-22 02:43:55,2026-03-22 03:07:50,2026-03-22 03:45:33,1970-01-01 00:00:00,1,0,0,0,trdtrdsd,中国,5000001,0,0,0,0,0,0,0,0,0,0,105,1878.0,41880,4.99,[],1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10763,2186,REED_W,14,3,2026-04-05 03:33:21,2026-04-05 02:47:26,2026-04-05 02:59:27,2026-04-05 03:33:06,1970-01-01 00:00:00,0,0,0,0,REED_W,United States,28,50730,490,3883,9890,935,1816,2037,5391,911,2683,409,2417.0,7840,0.96,"[{""attended"": true, ""trendDirection"": ""DOWN"", ...",3
11647,1829,PhoenixDD,14,3,2026-04-05 03:23:41,2026-04-05 02:42:12,2026-04-05 03:10:56,2026-04-05 03:13:34,1970-01-01 00:00:00,0,1,1,0,Dhairya Dhondiyal,United States,8,729260,4164,3893,15510,935,3335,2037,7896,921,4279,403,1765.0,4654,0.57,"[{""attended"": true, ""trendDirection"": ""UP"", ""p...",3
18249,1,VeritasVelata,20,4,2026-04-05 02:36:56,2026-04-05 02:31:18,2026-04-05 02:32:46,2026-04-05 02:34:38,2026-04-05 02:36:56,0,0,0,0,Veritas Velata,Sanctuary,19,18693,137,3893,4873,935,1212,2037,2589,921,1072,23,2332.0,25,0.01,"[{""attended"": true, ""trendDirection"": ""UP"", ""p...",3
3326,1329,SupremeChicken,18,4,2026-03-22 04:08:21,2026-03-22 02:39:13,2026-03-22 02:37:04,2026-03-22 02:55:52,2026-03-22 03:58:12,0,0,1,1,SupremeChicken,United States,21,4437,134,3893,21060,935,3149,2037,11348,921,6563,15,2272.0,5025,0.62,"[{""attended"": true, ""trendDirection"": ""UP"", ""p...",1
3088,275,watercyb,18,4,2026-03-22 03:12:48,2026-03-22 02:48:09,2026-03-22 02:42:42,2026-03-22 02:45:14,2026-03-22 03:00:39,1,0,0,1,watercyb,NaN,20,1214,22,3893,22336,935,3145,2037,10766,921,8425,22,2144.0,10034,1.22,"[{""attended"": true, ""trendDirection"": ""UP"", ""p...",1

In [26]:
lessProblems=df[(df['TotalQsAcc']<100) & (df['Rank']<5000)].copy()

lessProblems.head()

,Rank,User_slug,Score,CurrConSolved,FinishTimeStamp,Q1TimeStamp,Q2TimeStamp,Q3TimeStamp,Q4TimeStamp,Q1FailCnt,Q2FailCnt,Q3FailCnt,Q4FailCnt,UserName,CountryName,RankingP,PostViewCnt,Reputation,TotalQsAcc,TotalQsSub,EasyQsAcc,EasyQsSub,MedQsAcc,MedQsSub,HardQsAcc,HardQsSub,ContestCnt,CurrRating,GlobalRank,topPercentage,ContestHistory,contest_id
36,1712,Duck_You,12,3,2026-03-22 02:45:37,2026-03-22 02:32:14,2026-03-22 02:35:52,2026-03-22 02:45:07,1970-01-01 00:00:00,0,0,0,0,Duck_You,NaN,3495366,0,0,27,28,5,5,20,21,2,2,9,1802.0,64538,7.65,"[{""attended"": true, ""trendDirection"": ""UP"", ""p...",1
38,3612,user2784FH,12,3,2026-03-22 03:13:13,2026-03-22 02:32:28,2026-03-22 02:39:19,2026-03-22 03:13:10,1970-01-01 00:00:00,0,0,0,0,Ronny,NaN,3768790,0,0,23,24,16,17,7,7,0,0,12,1547.0,275931,32.29,"[{""attended"": true, ""trendDirection"": ""DOWN"", ...",1
50,4678,Charanbandi07,12,3,2026-03-22 03:23:13,2026-03-22 02:34:39,2026-03-22 02:42:15,2026-03-22 03:23:11,1970-01-01 00:00:00,0,0,0,0,Charanbandi07,India,1507938,0,0,99,143,57,80,39,55,3,8,31,1462.0,492344,57.32,"[{""attended"": true, ""trendDirection"": ""DOWN"", ...",1
51,1750,s1mply,12,3,2026-03-22 02:47:15,2026-03-22 02:33:42,2026-03-22 02:38:00,2026-03-22 02:46:13,1970-01-01 00:00:00,0,0,0,0,s1mply,NaN,4425253,4,0,16,18,11,13,5,5,0,0,1,1693.0,116968,13.78,"[{""attended"": true, ""trendDirection"": ""UP"", ""p...",1
54,4674,ankitverma969,12,3,2026-03-22 03:23:11,2026-03-22 02:37:25,2026-03-22 03:12:57,2026-03-22 02:54:28,1970-01-01 00:00:00,0,2,0,0,Ankit Verma,India,1580700,2,0,93,118,40,58,41,48,12,12,4,1721.0,99694,11.77,"[{""attended"": true, ""trendDirection"": ""UP"", ""p...",1

In [27]:
lessProblems.shape

(1549, 32)