In [1]:
print('hello')

hello

In [6]:
import pandas as pd
df=pd.read_csv('contest_496/weekly_contest496.csv')
df.head()

,Rank,User_slug,Score,CurrConSolved,FinishTimeStamp,Q1TimeStamp,Q2TimeStamp,Q3TimeStamp,Q4TimeStamp,Q1FailCnt,...,EasyQsSub,MedQsAcc,MedQsSub,HardQsAcc,HardQsSub,ContestCnt,CurrRating,GlobalRank,topPercentage,ContestHistory
0,1,VeritasVelata,20,4,1775356616,1.775356e+09,1.775356e+09,1.775356e+09,1.775357e+09,0.0,...,1212,2037,2589,921,1072,23,3321.441119,25,0.01,"[{""attended"": true, ""trendDirection"": ""UP"", ""p..."
1,2,ayushkumar980,20,4,1775356691,1.775356e+09,1.775356e+09,1.775356e+09,1.775357e+09,0.0,...,24,53,57,30,34,16,3109.443766,77,0.01,"[{""attended"": true, ""trendDirection"": ""UP"", ""p..."
2,3,raunak111,20,4,1775356699,1.775356e+09,1.775356e+09,1.775356e+09,1.775357e+09,0.0,...,198,196,274,41,44,8,1721.920546,99577,11.75,"[{""attended"": true, ""trendDirection"": ""DOWN"", ..."
3,4,Mona0405,20,4,1775356752,1.775356e+09,1.775356e+09,1.775356e+09,1.775357e+09,0.0,...,24,48,49,23,23,1,2058.391571,15295,1.85,"[{""attended"": true, ""trendDirection"": ""UP"", ""p..."
4,5,scale5558,20,4,1775356771,1.775356e+09,1.775356e+09,1.775356e+09,1.775357e+09,0.0,...,169,338,341,122,136,7,2283.780248,4752,0.58,"[{""attended"": true, ""trendDirection"": ""UP"", ""p..."

In [9]:
df.shape

(9408, 31)

In [12]:
df=pd.read_csv('contest_495/weekly_contest495.csv')
df.head()

,Rank,User_slug,Score,CurrConSolved,FinishTimeStamp,Q1TimeStamp,Q2TimeStamp,Q3TimeStamp,Q4TimeStamp,Q1FailCnt,...,EasyQsSub,MedQsAcc,MedQsSub,HardQsAcc,HardQsSub,ContestCnt,CurrRating,GlobalRank,topPercentage,ContestHistory
0,1,TechhnicalCode,19,4,1774751718,1.774752e+09,1.774752e+09,1.774752e+09,1.774752e+09,0.0,...,79,202,205,40,42,10,2332.074447,3688,0.45,"[{""attended"": true, ""trendDirection"": ""UP"", ""p..."
1,2,VeritasVelata,19,4,1774751783,1.774752e+09,1.774752e+09,1.774752e+09,1.774752e+09,0.0,...,1212,2037,2590,921,1072,23,3321.441119,25,0.01,"[{""attended"": true, ""trendDirection"": ""UP"", ""p..."
2,3,mann_1,19,4,1774751822,1.774752e+09,1.774752e+09,1.774752e+09,1.774752e+09,0.0,...,234,199,267,53,58,4,2096.897048,12675,1.53,"[{""attended"": true, ""trendDirection"": ""UP"", ""p..."
3,4,w7AOsRUeuu,19,4,1774751879,1.774752e+09,1.774752e+09,1.774752e+09,1.774752e+09,0.0,...,7,11,11,7,7,6,2467.140284,1914,0.23,"[{""attended"": true, ""trendDirection"": ""UP"", ""p..."
4,5,scale5558,19,4,1774751884,1.774752e+09,1.774752e+09,1.774752e+09,1.774752e+09,0.0,...,169,338,341,122,136,7,2283.780248,4752,0.58,"[{""attended"": true, ""trendDirection"": ""UP"", ""p..."

In [13]:
df.shape

(9377, 31)

In [14]:
df=pd.read_csv('contest_494/weekly_contest494.csv')
df.head()

,Rank,User_slug,Score,CurrConSolved,FinishTimeStamp,Q1TimeStamp,Q2TimeStamp,Q3TimeStamp,Q4TimeStamp,Q1FailCnt,...,EasyQsSub,MedQsAcc,MedQsSub,HardQsAcc,HardQsSub,ContestCnt,CurrRating,GlobalRank,topPercentage,ContestHistory
0,1,sunnynguyenai,18,4,1774147102,1.774147e+09,1.774147e+09,1.774147e+09,1.774147e+09,0.0,...,89,90,136,23,64,7,2347.059267,3415,0.42,"[{""attended"": true, ""trendDirection"": ""DOWN"", ..."
1,3,himank028,18,4,1774147143,1.774147e+09,1.774147e+09,1.774147e+09,1.774147e+09,0.0,...,2,6,6,5,6,3,2188.433504,7859,0.96,"[{""attended"": true, ""trendDirection"": ""UP"", ""p..."
2,4,hfgdnnvnxfg,18,4,1774147151,1.774147e+09,1.774147e+09,1.774147e+09,1.774147e+09,0.0,...,7,14,14,7,7,1,2047.222137,16114,1.95,"[{""attended"": true, ""trendDirection"": ""UP"", ""p..."
3,5,dark_knight_bt,18,4,1774147191,1.774147e+09,1.774147e+09,1.774147e+09,1.774147e+09,0.0,...,345,300,636,51,81,52,2449.597491,2061,0.25,"[{""attended"": true, ""trendDirection"": ""DOWN"", ..."
4,6,ayushkumar980,18,4,1774147203,1.774147e+09,1.774147e+09,1.774147e+09,1.774147e+09,0.0,...,24,53,57,30,34,16,3109.443766,77,0.01,"[{""attended"": true, ""trendDirection"": ""UP"", ""p..."

In [16]:
df.shape

(9138, 31)